1 feature user opens the program
CSC207-2022F-UofT/course-project-my-dog-ate-my-hw pull request #25
Opened 2022-11-16 23:52 UTC by stephaniesaab

Created the ToDoList class with its private attribute (taskList) and its two public methods (addTask and removeTask). Javadocumentation for the class, its attribute and each method is added as well.

2022-11-17 04:39 UTC, harshsbajwa requested changes
Please change "Entities" to "entities" for consistency

2022-11-17 04:39 UTC, harshsbajwa commented on src/main/java/Entities/ToDoList.java
> +package Entities;
We decided that entities would be lowercase (for consistency and in accordance with the demo repository), please change

2022-11-17 14:23 UTC, XinyingXu commented on src/main/java/Entities/DoneList.java
> +    public DoneList() {
You could add another constructor which takes in a list as parameters, which could be used later by use cases.

2022-11-17 14:42 UTC, XinyingXu commented on src/main/java/Entities/ToDoList.java
> +
My use case might need a searchFor(String taskName) method to locate a task in the list and return the Task object.

2022-11-19 05:46 UTC, serenahonekin requested changes
Could you also sort the ToDoList by the task's deadline?

2022-11-21 23:30 UTC, e-laflamme approved these changes
Looks good! You may want to leave out the gradle files when committing in the future though. 
Before merging, you should probably change the entities folder name and import statements to lowercase.

2022-11-22 04:47 UTC, merged