Pet Adoption Feature
CSC207-2022F-UofT/course-project-my-dog-ate-my-hw pull request #27
Opened 2022-11-17 03:05 UTC by e-laflamme

Contains all the code necessary to create a UI for the pet shop, allowing the user to select a pet and name it. From this selection, a pet object is created and stored in the PetShopDisplayer. 

**Work to be done:** The Pet needs to be assigned to the User. This should be done from the main program using the Pet Object stored in PetShopDisplayer.

_Note: All images in the petIcon folder are not ours; they are placeholders and will be changed before final_

2022-11-19 14:32 UTC, XinyingXu commented on src/main/java/entities/Pet.java
>  }
When creating a pet, the pet should have a default list of customizations already filled and all locked. I think that will be handled by AdoptPet use case, but you can have a setter method setCustomization for the entity.

2022-11-20 02:39 UTC, e-laflamme commented on src/main/java/entities/Pet.java
>  }
I think that we are leaning towards having the Customization object store a list of default customization options. Harsh and I need to discuss it a bit to see how to implement this. The constructor of Pet will handle setting the value of customization so that its not something that can be changed once set. We do need a method in the usecase or one of the entities to set the default customizations. I think we can just add this in an update.

2022-11-20 23:32 UTC, stephaniesaab commented on src/main/java/Entities/User.java
> -    int Points;
Please change the names of the TODO  and DONE lists to 'ToDoList and 'DoneList' respectively.

2022-11-20 23:34 UTC, stephaniesaab commented on src/main/java/Entities/User.java
> +    private int Points;
These attributes (Points and MyPet) should have a lowercase letter at the start of their name.

2022-11-20 23:47 UTC, XinyingXu commented on src/main/java/Entities/User.java
> +    private int Points;
> These attributes (Points and MyPet) should have a lowercase letter at the start of their name.

User.java is already settled in main branch. You could just delete this file from your pull request to resolve conflicts.

2022-11-20 23:48 UTC, e-laflamme commented on src/main/java/Entities/User.java
> +    private int Points;
Will do! Sorry about that

2022-11-20 23:52 UTC, e-laflamme commented on src/main/java/Entities/User.java
> +    private int Points;
Okay I tried to do that but it seemed like it was actually going to delete the file from main once my pull is merged... Are you sure it won't?

2022-11-20 23:57 UTC, XinyingXu commented on src/main/java/Entities/User.java
> +    private int Points;
> Okay I tried to do that but it seemed like it was actually going to delete the file from main once my pull is merged... Are you sure it won't?

I think you will only delete them from your own pull request. If after deletion it says "This branch has no conflicts with the base branch", you should be fine.

2022-11-21 00:11 UTC, harshsbajwa approved these changes
After fixing merge conflicts, this PR should be fine to merge. Item and Customization have changed so changes might be needed. Just a few remarks:

a) greater documentation would be helpful in PetShopWindow to make sense of all the panels. This will make future changes easier.

b) we want to leave ourselves open for accessibility and a dark-mode (?), thus we should be wary of the magic values and colours in PetShopWindow

c) ImageIcon is not an entity, so we should be wary of including it in the Pet entity.

2022-11-21 00:13 UTC, XinyingXu commented on src/main/java/Entities/User.java
> +    private int Points;
> Okay I tried to do that but it seemed like it was actually going to delete the file from main once my pull is merged... Are you sure it won't?

Oh sorry wait I'm not so sure for now. Seems like it will delete from main. Please follow Harsh's comments, so sorry for my previous comments.

2022-11-21 00:51 UTC, merged

2022-11-21 01:22 UTC, stephaniesaab requested changes
Hi Emily, this looks great! I see a few places where a design pattern may be implemented and I've mentioned those. There's no need to include them in the changes but consider them for future enhancements. Changes to documentation and names for attributes and methods would be helpful to keep it consistent with the rest of the program (specifically the ToDoList and DoneList).