Feature 3: User creates a task
CSC207-2022F-UofT/course-project-my-dog-ate-my-hw pull request #33
Opened 2022-11-19 06:38 UTC by serenahonekin

2022-11-19 14:06 UTC, XinyingXu requested changes

2022-11-19 14:06 UTC, XinyingXu commented on src/main/java/entities/Task.java
> +
Please add a getter getStudyDeadline which returns the studyDeadline.

2022-11-19 14:48 UTC, XinyingXu commented on src/main/java/entities/Task.java
> +}
Maybe we don't need the completion boolean, because the location of the task (in Todo/Done list) says everything about if it's completed or not.

2022-11-19 22:34 UTC, e-laflamme requested changes
Good work! There are a couple things that should be changed before merging though. I have left comments on the specific parts of the files that I see some issues with.

2022-11-19 22:34 UTC, e-laflamme commented on src/main/java/entities/CustomTask.java
> +import java.time.LocalDateTime;
In the abstract Task class (the one in src/java/main) you used the data type Date. Here, in the Task in the entities folder, and in the usecase, the type used is LocalDateTime. Not sure if the abstract class is just an old implementation, just wanted to point it out to make sure things stay consistent.

2022-11-19 22:34 UTC, e-laflamme commented on src/main/java/entities/Task.java
> +public class Task {
Why are there two Task classes? There is this one and then there is the abstract class. Need to chose one for consistency. I recommend keeping this one and getting rid or the abstract class as I do not see it being used anywhere and it makes more sense for task to be non-abstract.

2022-11-19 22:34 UTC, e-laflamme commented on src/main/java/entities/Task.java
> +        this.studyDeadline = deadline.plusDays(3);
plusDays(3) is adding three days to the deadline, meaning it is 3 days after deadline. I would think the study deadline should be before the actual deadline so you should use minusDays(3) instead.

2022-11-19 22:34 UTC, e-laflamme commented on src/main/java/entities/Task.java
> +}
I think it would be best to store its completion status so that when we load all the tasks in from wherever we save them, the program knows which are completed and which are not.

2022-11-19 23:15 UTC, XinyingXu commented on src/main/java/Task.java
> +    enum Priority {
> This enum may have use outside of this class. I am not sure that in its current state it will be accessible to all outside classes. I would recommend making it its own class.
> 
> In IntelliJ when you click New Class, you can select to make an Enum class. You would pretty much just copy and paste the couple lines of code you have for it here. It can be put in the entities folder.

I have made a Priority class in my PR (the checks off task one) to make use of it in my use case, you could consult it so there are no conflicts between our code :)

2022-11-20 17:41 UTC, sing1348 commented
<img width="1049" alt="Screenshot 2022-11-20 at 12 38 00 PM" src="https://user-images.githubusercontent.com/113359038/202917242-ace07fdf-1208-458c-970b-472c3f7f0366.png">

instead of giving the user a free string for assignment type, we need to perhaps give them an input prompt asking to choose between the different pre-determined types eg: exam revision, quiz, research paper, and so on. Without this, it is very hard for me to implement feature 8, which includes suggesting the user which type of study technique to use based on assignment type

2022-11-21 23:19 UTC, e-laflamme approved these changes
Changes look good!

2022-11-21 23:23 UTC, XinyingXu approved these changes
Great job done!

2022-11-22 01:52 UTC, sing1348 approved these changes

2022-11-22 01:52 UTC, sing1348 commented on src/main/java/Task.java
> +    private boolean completion;
Made the suggestion to: add assignment type as a parameter. This was critical for implementation of the feature "suggest study techniques" as this is to be done based on the assignment type

2022-11-22 01:52 UTC, sing1348 commented on src/main/java/entities/AssignmentType.java
> +public enum AssignmentType {
provided suggestion to change assignmentType from a private string to a public enum - multiple classes outside would later have to access this variable and thus it should be private to avoid errors later. As per the current scope of the program, we decided to provide enum instead of an open string type as this would provide only fixed variables the user would choose from would be these predetermined ones.

2022-11-22 01:52 UTC, sing1348 commented on src/main/java/entities/CustomTask.java
> +    private String studyTechniques;
StudyTechniques are to be accessed by different classes outside - better to make it public

2022-11-22 01:52 UTC, sing1348 commented on src/main/java/entities/CustomTask.java
> +    public String getStudyTechniques() {
getStudyTechniques is an entity : a class and thus instead of declaring a separate variable here, simply use that class

2022-11-22 01:52 UTC, sing1348 commented on src/main/java/useCase/CreateTaskUC.java
> +    public Task createTask(String name, String course, LocalDateTime deadline, Priority priority, String studyTechniques, AssignmentType assignmentType) {
make study techniques optional

2022-11-22 03:25 UTC, merged