Feature 7: User wants to buy a hat for the pet
CSC207-2022F-UofT/course-project-my-dog-ate-my-hw pull request #39
Opened 2022-11-21 11:27 UTC by chrischin1

Created BuyHatUC which implements the specified use case for a User wanting to purchase a Hat for their pet, as well as the respective test file BuyHatUCTest.

2022-11-21 15:31 UTC, XinyingXu commented on src/main/java/useCases/BuyHatUC.java
> +        }
If the hat is already unlocked, it would just get equipped upon clicking. Maybe you can split the cases of the hat as if it's unlocked or locked; if the pet is equipped with a hat or not.

2022-11-22 02:11 UTC, e-laflamme requested changes

2022-11-22 02:11 UTC, e-laflamme commented on src/main/java/useCases/BuyHatUC.java
> +        if (user.getPoints() >= hat.price) {
Since this if statement runs before the next, even if the user has already bought the hat, they will still get charged for it. You could add another if statement to check if the hat is already unlocked first.

2022-11-22 02:38 UTC, chrischin1 commented on src/main/java/useCases/BuyHatUC.java
> +        if (user.getPoints() >= hat.price) {
Thanks :)

2022-11-22 02:42 UTC, XinyingXu approved these changes

2022-11-22 02:42 UTC, XinyingXu commented on src/main/java/useCases/BuyHatUC.java
> +        }
The changes look good!

2022-11-22 02:45 UTC, harshsbajwa approved these changes
Looks good, no complaints

2022-11-22 02:45 UTC, harshsbajwa commented on src/main/java/entities/Customization.java
>          customizations.remove(item);
change "PRIVATE" to "PUBLIC" on line 8 of Customization

2022-11-22 02:57 UTC, e-laflamme approved these changes
Make sure to make fixes for next PR :)

2022-11-22 02:57 UTC, serenahonekin approved these changes
Everything looks good to me!

2022-11-22 02:59 UTC, merged