Feature 3 user creates a task
CSC207-2022F-UofT/course-project-my-dog-ate-my-hw pull request #61
Opened 2022-12-05 02:10 UTC by serenahonekin

# Description

Modified the previous task entity, use case and controller. Added tests and documentation. Pulled from main.

Fixes # 3

## Type of change

- [ ] Compilation error fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation
- [x] Test cases
- [x] Redundant code removal (fix code smells)
- [ ] Data storage 
- [ ] UI element

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-05 21:52 UTC, XinyingXu requested changes

2022-12-05 21:52 UTC, XinyingXu commented on src/main/java/entities/Priority.java
> +    Medium,
"Medium" should be all upper case "MEDIUM".

2022-12-06 23:05 UTC, stephaniesaab requested changes
Overall, the code looks good. There are a few modifications that need to be made to the controller class so that it depends on the input boundary instead of the use case interactor. Also, the test suites can implement the @before annotation to improve readability and remove redundant code.

2022-12-06 23:05 UTC, stephaniesaab commented on src/test/java/useCases/CreateTaskUCTest.java
> +    @Test
For these tests, there's lots of duplicate code making tasks and parsing dates. Try using the @Before annotation and create a setUp method that can create the tasks once and then they can be used throughout the test suite. It'll also reset the value of the tasks so that if you change a task attribute in one test, the next test will have the originally initiated attribute.

2022-12-06 23:19 UTC, XinyingXu commented on src/main/java/useCases/CreateTaskInputBoundary.java
> +    void createTask(String name, String course, LocalDateTime deadline, Priority priority, AssignmentType assignmentType);
I think it best to have this method take in a String priority and String assignment type, and parse them into enum objects inside the method because input boundaries are responsible for parsing input data into the data format suitable for our entities. Remember to make corresponding changes to your use case too.

2022-12-08 03:49 UTC, merged