[Feature 14] User Modifies a Task + documentations, tests
CSC207-2022F-UofT/course-project-my-dog-ate-my-hw pull request #66
Opened 2022-12-05 22:05 UTC by serenahonekin

# Description

Changed user modifies a task use case to have an input boundary and to correspond with the task class. Added tests and documentation.

Fixes # 14

## Type of change

- [ ] Compilation error fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] Test cases
- [ ] Redundant code removal (fix code smells)
- [ ] Data storage 
- [ ] UI element

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-06 18:03 UTC, XinyingXu requested changes

2022-12-06 18:03 UTC, XinyingXu commented on src/main/java/useCases/ModifyTaskUC.java
> +
Maybe I have missed something, but what is this "todo" referring to? Maybe you should take in an "entities.User user" and String taskName as input, and perform actions on user.getToDo().

2022-12-06 22:34 UTC, stephaniesaab approved these changes
This is a solid implementation of clean architecture, the tests are sufficient in testing each method. There could be minor modifications just to make them extra confident but otherwise it's very good.

2022-12-06 22:34 UTC, stephaniesaab commented on src/main/java/uiControllers/ModifyTaskController.java
> +
Since this class is just a placeholder for now, just ensure to document it once its been implemented.

2022-12-06 22:34 UTC, stephaniesaab commented on src/main/java/useCases/ModifyTaskInputBoundary.java
> + * The input boundary for the ModifyTask use case which passes information from the controller.
Good documentation

2022-12-06 22:34 UTC, stephaniesaab commented on src/test/java/useCases/ModifyTaskUCTest.java
> +        Assertions.assertEquals(AssignmentType.QUIZ, task.getAssignmentType());
For the future, the test suite can be more complete by adding tests for each assignment type as it has a defined set of values and that can all be tested.

2022-12-06 23:51 UTC, XinyingXu commented on src/main/java/useCases/ModifyTaskUC.java
> +
We should check the uniqueName criteria before actually changing the name.

2022-12-07 21:25 UTC, XinyingXu approved these changes
All the changes are good and meet the project requirements.

2022-12-07 22:27 UTC, merged